services:
  postgres:
    image: postgres:latest
    container_name: practice5-postgres
    restart: always
    healthcheck:
      test:
        ["CMD", "pg_isready", "-q", "-d", "practice5", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: practice5
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    container_name: practice5-app
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: practice5
    depends_on:
      - postgres
volumes:
  postgres-data:
