version: "3.8"
services:
  apache:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./index.php:/var/www/html/index.php
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
